### ISSUE TITLE
reactor.core.Exceptions$OverflowException

### ISSUE THREAD

**Issue by ksinghbora** [reactor/reactor-kafka#34] opened 2018-06-19 09:46 UTC
While running time taking flow, I am getting exception:

```
19 Jun; 14:12:21.039 [reactive-kafka-consumer-groupId-116] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$OverflowException: Could not emit tick 1232 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
Caused by: reactor.core.Exceptions$OverflowException: Could not emit tick 1232 due to lack of requests (interval doesn't support small downstream requests that replenish slower than the ticks)
    at reactor.core.Exceptions.failWithOverflow(Exceptions.java:215)
    at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:130)
    at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
    at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by OlegDokuka** [comment] 2018-06-26 20:56
Hello @ksinghbora! Could you please provide some steps to reproduce that issue and version of Reactor-Kafka and Reactor that you use in your case? Thanks

**Comment by OlegDokuka** [comment] 2018-07-07 20:11
looks like a duplicate of #29

**Comment by OlegDokuka** [comment] 2018-07-09 15:47
fixed by #40

**Closed by OlegDokuka** 2018-07-09 15:47 UTC
Labels: duplicate

**Comment by ksinghbora** [comment] 2018-07-10 03:15
@OlegDokuka Thanks.
