### ISSUE TITLE
Concurrent Processing with Partition-Based Ordering w/ Manual Acknowledgement - Race Condition on Rebalance

### ISSUE THREAD

**Issue by damianlarson** [reactor/reactor-kafka#240] opened 2021-09-10 21:39 UTC
Maybe this is just an issue with our specific implementation of this, but we're seeing unexpected behavior that's causing problems when rebalancing happens.

In our current process, we're using concurrent processing with partition-based ordering with the intention being to consume each partition sequentially on the same set of threads, as described in the reactor-kafka docs. In our process, we check to see if we're assigned the partition before processing--if so, we continue, if not, we return--and we also check after processing if we still have the partition assigned. If we have the partition assigned after processing, we make the manual acknowledgement, and reactor will make the commits when it needs to. What we're seeing is that when partitions are revoked, the Flux continues to have messages. The problem here lies in the asynchronicity, if a partition is re-assigned a partition while the Flux is still processing a message, we will process it successfully, see that we own the partition, and acknowledge the offset, which will acknowledge all of the offsets before, even though we didn't actually process those messages. Sample code is shown below, but it appears to be a race condition where the Flux is not re-initialized (or purged) when Kafka takes the partitions, even though they should be.

## Expected Behavior

Flux is drained/reinitialized when Kafka revokes partitions. Docs for ReceiverOptions indicate that `when group management is used, revoke listeners are invoked before every rebalance operation`, which if true, the above behavior is not in line with Kafka's docs for the `ConsumerRebalanceListener`, which indicate that `in eager rebalancing, it will always be called at the start of a rebalance and after the consumer stops fetching data.`

## Actual Behavior

Messages persist on the Flux and are successfully processed, which will cause a race condition if the same partition is later re-assigned.

## Steps to Reproduce

Our consumer is as follows:
```java
ReceiverOptions<Integer, String> options = ReceiverOptions.create(props);
receiverOptions = options.subscription(getTopicAndReplica(topic))
        .addAssignListener(partitions -> {
            assignedPartitions = partitions;
            log.info("{} Partitions Assigned {}", name, AOUtilities.printPartitions(partitions));
        })
        .addRevokeListener(partitions -> {
            assignedPartitions.clear();
            log.info("{} Partitions Revoked {}", name, AOUtilities.printPartitions(partitions));
        })
        .commitInterval(Duration.ofSeconds(1))
        .commitBatchSize(1)
        .closeTimeout(Duration.ofSeconds(30))
        .pollTimeout(Duration.ofSeconds(5));
        
receiver = KafkaReceiver.create(receiverOptions);

scheduler = Schedulers.newBoundedElastic(Schedulers.DEFAULT_BOUNDED_ELASTIC_SIZE, Integer.MAX_VALUE, schedulerThreadName, 60, false);

receiver.receive().groupBy(m -> m.receiverOffset().topicPartition())
      .flatMap(partitionFlux -> partitionFlux.publishOn(scheduler)
                                  .map(r -> {
                                      if (isAssignedPartition(r)) {
                                          eventConsumer.consumeEvent(r, name);
                                          if (isAssignedPartition(r)) {
                                              r.receiverOffset().acknowledge();
                                              updatePartitionOffset(r);
                                          } else {
                                              log.info("Event Dropped: Partition {} not exists with {} anymore after processed. Results a duplicate", r.receiverOffset(), name);
                                          }
                                          return r;
                                      } else {
                                          log.info("Event Dropped: Partition {} not exists with {} anymore", r.receiverOffset(), name);
                                          return Mono.just(r);
                                      }
                                  })
      )
      .subscribe();
```

The `isAssignedPartition()` method simply checks the in-memory `assignedPartitions` map, which you'll see gets set and cleared on assignment and revocation respectively.

To reproduce, you can run two instances of this same consumer within the same consumer group. Ensure that the consumer group has plenty of lag. Keep one of the instances on at all times, and cycle the other one on and off repeatedly. When this happens, occasionally messages will be consumed by the primary instance between the time that partitions are revoked and before new partitions are assigned, which the logs below show:

```
[reactive-kafka-CONSUMER_GROUP-12] 15:20:43.774 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - EmailConsumer Partitions Revoked [ --email.v1_1, --email.v1_2, --email.v1_0, --email.v1_9, --email.v1_7, --email.v1_8, --email.v1_5, --email.v1_6, --email.v1_3, --email.v1_4,  ]

15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249026 not exists with EmailConsumer anymore after processed. Results a duplicate
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249027 not exists with EmailConsumer anymore
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249028 not exists with EmailConsumer anymore
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249029 not exists with EmailConsumer anymore
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249030 not exists with EmailConsumer anymore
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249031 not exists with EmailConsumer anymore
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249032 not exists with EmailConsumer anymore
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249033 not exists with EmailConsumer anymore
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249034 not exists with EmailConsumer anymore
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249035 not exists with EmailConsumer anymore
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249036 not exists with EmailConsumer anymore
15:20:43.784 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - Event Dropped: Partition test-topic.v1-1@7249037 not exists with EmailConsumer anymore
[reactive-kafka-CONSUMER_GROUP-12] 15:20:43.774 INFO  c.c.f.m.a.o.c.FluxDeferConsumer            - EmailConsumer Partitions Assigned [ --email.v1_17, --email.v1_18, --email.v1_15, --email.v1_16, --email.v1_13, --email.v1_14, --email.v1_11, --email.v1_12, --email.v1_19, --email.v1_1, --email.v1_2, --email.v1_0, --email.v1_9, --email.v1_10, --email.v1_7, --email.v1_8, --email.v1_5, --email.v1_6, --email.v1_3, --email.v1_4,  ]
```

In this scenario, it was re-assigned the same partition, but not coincidentally during the time that a message was processing. Race conditions are hard to reproduce, but the behavior of "messages processed after revocation" still happens.

## Your Environment

* Reactor version(s) used: 1.3.5
* Other relevant libraries versions (eg. `netty`, ...): Spring MVC 2.5.4
* JVM version (`java -version`): openjdk:8-alpine
* OS and version (eg `uname -a`): Alpine Linux 3.10

**Comment by garyrussell** [comment] 2021-09-13 15:02
> which will acknowledge all of the offsets before, even though we didn't actually process those messages.

The javadocs clearly state that is the behavior - the application is responsible to ack the records in the right order.

We recently added a new feature in Spring for Apache Kafka to support out-of-order acks (by deferring commits that are beyond a gap).

Before that, applications there also had to keep track of offsets and commit them in the right order.

https://docs.spring.io/spring-kafka/docs/2.8.0-SNAPSHOT/reference/html/#x28-ooo-commits

I am considering doing something similar here.

I haven't looked closely, yet, but I am guessing that the behavior you are seeing is because there are records already in the pipeline from the previous poll when the rebalance occurs.

**Comment by simonbasle** [comment] 2021-09-22 10:22
@garyrussell should this issue be used to track the potential new feature, or should a separate issue be opened?

**Comment by garyrussell** [comment] 2021-09-23 17:35
https://docs.spring.io/spring-kafka/docs/2.8.0-SNAPSHOT/reference/html/#x28-ooo-commits

We should leave this open while I look to see if my assumption is correct.

**Comment by srinivasvsk** [comment] 2022-04-19 14:39
Any update to this issue

**Comment by garyrussell** [comment] 2022-04-19 15:21
Out of order commits are now supported.

https://github.com/reactor/reactor-kafka/pull/253

https://projectreactor.io/docs/kafka/release/reference/#_out_of_order_commits

**Comment by srinivasvsk** [comment] 2022-04-19 17:57
thanks , got curious with this issue still in open status

**Comment by qavid** [comment] 2022-04-23 19:23
@garyrussell We have a similar problem, but I think the root cause is the same as you guessed already: 

> I haven't looked closely, yet, but I am guessing that the behavior you are seeing is because there are records already in the pipeline from the previous poll when the rebalance occurs.

Do you think it would be possible to to reinitialize sink in ConsumerHandler after partition is assigned/revoked?

The most problematic part is start of applications in cluster when rebalance occurs multiple times and so are records fetched (and processed) multiple times (even by the exactly same consumer instance).

To minimize number of records to be processed multiple times, you can lower ConsumerConfig.MAX_POLL_RECORDS_CONFIG and prefetch for groupBy operator.

Simple test to reproduce problem:
```kotlin
@Test
fun reproCase() {
	val consumerProps = Map.of<String, Any>(
		ConsumerConfig.GROUP_ID_CONFIG, "g1",
		ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092",
		ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest",
		//ConsumerConfig.MAX_POLL_RECORDS_CONFIG, 10
	)
	val consumerOpts = ReceiverOptions.create<String, String>(consumerProps)
		.commitBatchSize(0)
		.commitInterval(Duration.ZERO)
		.withKeyDeserializer(StringDeserializer())
		.withValueDeserializer(StringDeserializer())
		.subscription(Collections.singleton(TEST_TOPIC)) // Test topic should have 2+ partitions

	val consumer1 = KafkaReceiver.create(consumerOpts).process()

	Thread.sleep(10000L) // Force a re-balance
	val consumer2 = KafkaReceiver.create(consumerOpts).process()

	Thread.sleep(10000L)
	consumer1.dispose()
	consumer2.dispose()
}

fun KafkaReceiver<String, String>.process() =
	receive()
		.log("groupBy")
		.groupBy({ it.receiverOffset().topicPartition() }/*, 1*/)
		.flatMap { partitionFlux ->
			partitionFlux
				.publishOn(Schedulers.parallel())
				.delayUntil { record ->
					Mono.delay(Duration.ofSeconds(1))
						.then(record.receiverOffset().commit()
							.doOnSuccess { logger.info { "Record from ${record.receiverOffset()} committed" } }
						)
				}
		}
		.subscribe()
```

After consumer2 is subscibed and partitions are reassigned, you can see duplicated commits for the same receiver offset. (Assumption: to consumer2 is assigned the same partition which consumer1 started processing at the beginning of the test)

**Comment by garyrussell** [comment] 2022-04-25 16:42
@qavid I don't see any API to drain the sink. In any case, if I understand things correctly, you will have already drained it with your `groupBy` and `flatMap` - the records are no longer in the initial sink, they are now further down the pipeline.

cc/ @simonbasle

**Comment by qavid** [comment] 2022-04-25 23:33
@garyrussell you are right, but if I simplify previous sample to:
```kotlin
fun KafkaReceiver<String, String>.process(name: String) =
	receive()
		.log("concatMap")
		.concatMap({ record ->
			record.toMono()
				.delayUntil { Mono.delay(Duration.ofSeconds(4)) }
				.then(record.receiverOffset().commit()
					.doOnSuccess { logger.info { "Record from ${record.receiverOffset()} committed by $name" } }
				)
		}, 1)
```
all records will be in upstream and as a client I have no way to filter out records fetched before rebalance.

One way would be to associate each record with `ConsumerGroupMetadata` (or at least generationId) at the time of poll and later filter out records by current generationId.
`.filter { record -> record.consumerGroupMetadata()?.generationId() == currentGenerationId }`

The other way would be to filter out records by currently assigned partitions and after rebalance seek to the last fetched offset.

**Comment by polrsg** [comment] 2022-06-12 12:14
@garyrussell @simonbasle Hey, I'm using out-of-order commits and interval commits (using manual acknowledge for each message). I've read this issue and that makes me wonder what will happen if I'll process messages that I polled before the rebalance, while they are currently processed asynchronously in another thread (using `publishOn(Schedulers.parallel())` after the `kafkaReceiver.recieve()`). 

Will they be committed after the rebalance while the partition may be consumed by a new consumer? I want to avoid this situation which can lead to processing event at the same time by two consumer since that can cause race and conflicts (that I need to avoid). 

I'll be ok with processing an event that was polled before the rebalance only if I won't acknowledge and commit it. That's because then the new consumer will process this message after the rebalance either (I'm working with 'at least once' strategy so that's fine).

How can I achieve this behavior? Does checking if the event's source partition belongs to the assign partitions before acknowledging is a good option? 
Or is there any way of forcing the acknowledge function to fail if it's an event of old partition that is not currently assigned by the consumer?

**Comment by garyrussell** [comment] 2022-06-13 14:16
As discussed here https://github.com/reactor/reactor-kafka/issues/266#issuecomment-1130421580 we need to assign an epoch to the receiver records.

**Closed** 2022-07-13 17:23 UTC
Labels: type/enhancement, status/need-decision, for/user-attention
