### ISSUE TITLE
Partitions re-assignation is not handled correctly

### ISSUE THREAD

**Issue by gzeskas** [reactor/reactor-kafka#49] opened 2018-07-27 07:51 UTC
When I have some problem processing received messages from kafka via reactor-kafka and my processing time took longer then max.poll.interval.ms partitions that my consumer was assigned to are revoked from that consumer and that is ok, the problem is that reactor-kafka is not re-binding to those partitions as I have discovered there is an event from kafka-client that client had re-joined but no messages are received vie reactor-kafka more till full service restart. I have attached some log files
```
2018-07-27 10:41:38.934  INFO 27672 --- [rvice.traffic-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=storage-service.traffic] Setting newly assigned partitions [traffic-0]
2018-07-27 10:41:38.935  INFO 27672 --- [rvice.traffic-1] c.c.s.s.kafka.ReactiveTrafficListener    : onPartitionsAssigned [traffic-0] 
2018-07-27 10:42:02.370  INFO 27672 --- [ice.traffic-bin] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-2, groupId=storage-service.traffic-bin] Marking the coordinator bd-vagrant:9092 (id: 2147483647 rack: null) dead
2018-07-27 10:42:02.564  INFO 27672 --- [service.traffic] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=storage-service.traffic] Marking the coordinator bd-vagrant:9092 (id: 2147483647 rack: null) dead
2018-07-27 10:42:02.623  INFO 27672 --- [rvice.traffic-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=storage-service.traffic] Discovered group coordinator bd-vagrant:9092 (id: 2147483647 rack: null)
2018-07-27 10:42:02.629 ERROR 27672 --- [rvice.traffic-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=storage-service.traffic] Offset commit failed on partition traffic-0 at offset 41273: The coordinator is not aware of this member.
2018-07-27 10:42:04.455  INFO 27672 --- [e.traffic-bin-2] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-2, groupId=storage-service.traffic-bin] Discovered group coordinator bd-vagrant:9092 (id: 2147483647 rack: null)
2018-07-27 10:42:04.458  WARN 27672 --- [rvice.traffic-1] r.k.r.internals.DefaultKafkaReceiver     : Commit failed

org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:787)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:735)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:814)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:794)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:204)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:167)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:127)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:507)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:353)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:268)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:214)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1164)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1111)
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver$PollEvent.run(DefaultKafkaReceiver.java:446)
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.doEvent(DefaultKafkaReceiver.java:377)
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$start$16(DefaultKafkaReceiver.java:319)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:396)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:480)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2018-07-27 10:42:04.459 ERROR 27672 --- [rvice.traffic-1] r.k.r.internals.DefaultKafkaReceiver     : Consumer flux exception
org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:787)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:735)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:814)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:794)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:204)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:167)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:127)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:507)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:353)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:268)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:214)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1164)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1111)
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver$PollEvent.run(DefaultKafkaReceiver.java:446)
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.doEvent(DefaultKafkaReceiver.java:377)
	at reactor.kafka.receiver.internals.DefaultKafkaReceiver.lambda$start$16(DefaultKafkaReceiver.java:319)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:130)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:396)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:480)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-07-27 10:42:04.470  INFO 27672 --- [rvice.traffic-1] c.c.s.s.kafka.ReactiveTrafficListener    : onPartitionsRevoked [traffic-0]
2018-07-27 10:42:04.471  INFO 27672 --- [rvice.traffic-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=storage-service.traffic] (Re-)joining group
2018-07-27 10:42:10.478  INFO 27672 --- [e.traffic-bin-2] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-2, groupId=storage-service.traffic-bin] Successfully joined group with generation 7
2018-07-27 10:42:10.479  INFO 27672 --- [e.traffic-bin-2] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-2, groupId=storage-service.traffic-bin] Setting newly assigned partitions [traffic-bin-0]
```
And no more messages from reactor-kafka that partitions were assigned, I'm using latest release: 1.0.1 tried also with 1.0.0 the same issue.

**Comment by OlegDokuka** [comment] 2018-07-27 07:55
@gzeskas, thank you for that issue. I will investigate that and fix ASAP!

**Comment by gzeskas** [comment] 2018-08-24 10:39
@OlegDokuka 
I made a workaround for this issue. I simple re-create entire reactive stream onTerminate as what I have discovered that reactor-kafka on any exception from kafka-client is closing all the internal and external Flux, it's simple doing dispose and it's not able to recover.

I tried to comment out error submission in fail method:
```
    private void fail(Throwable e) {
        log.error("Consumer flux exception", e);
        //recordSubmission.error(e);
    }
```
And then it's recovering from this this re-partition situation,  but I don't think that it's a solution to skip all exceptions from kafka-client, maybe any ideas how it could be handled more gracefully ?

**Comment by travikk** [comment] 2018-11-18 00:11
@OlegDokuka any update on the issue?

**Comment by ashansa** [comment] 2018-11-30 14:05
I am facing the same issue and kafka stopped processing any messages after this. It would be awesome to know any updates about the issue.

**Comment by travikk** [comment] 2018-12-21 05:37
@OlegDokuka is there any work being done on this issue?

**Comment by FcoJavierSainz** [comment] 2019-02-13 19:43
@simonbasle Do you know is somebody from Pivotal will be assigned to this project?

**Comment by yevtsy** [comment] 2019-02-26 16:01
As @gzeskas noticed, the main reason for this issue is that handler [here](https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L480)
```
if (isActive.get()) {
     log.error("Unexpected exception", e);
     fail(e);
}
```
closes all the chain in case of any error. 
I think we can treat the issue in the way as it was offered in Kafka stream error handling.
As was proposed [KIP-161](https://cwiki.apache.org/confluence/display/KAFKA/KIP-161%3A+streams+deserialization+exception+handlers) we can introduce configurable property which determines how to handle consumer exceptions: log it and continue processing or just fail and stop

@OlegDokuka @simonbasle

**Comment by OlegDokuka** [comment] 2019-02-26 19:38
FYI, I will be working a few next weeks on bug-fixing and newer version of reactor-Kafka. Stay tuned

**Comment by arnaldo82** [comment] 2019-03-27 18:30
Hi @OlegDokuka 
Is there an estimation date on when 1.0.2 release will be ready ?

Thanks

**Comment by neko-gg** [comment] 2019-04-01 19:34
Hi guys, I added an exception handler for the reactive receiver, similiar to what was proposed in [KIP-161](https://cwiki.apache.org/confluence/display/KAFKA/KIP-161%3A+streams+deserialization+exception+handlers) for kafka-streams.

You can simply pass this extra configuration in your receiver options, like this:
```
receiverOptions.receiverExceptionHandler(new LogAndContinueReceiverExceptionHandler())
```

There's also `LogAndFailReceiverExceptionHandle` that is basically the current behavior (and this is the default if the configuration above is missing).

The interface `ReceiverExceptionHandler` is freely and easily implementable, so that everyone can choose on which exception to `Continue` and on which to `Fail`.

**Comment by yevtsy** [comment] 2019-04-22 11:04
@gzeskas @travikk 
please check the fix provided by @neko-gg. It's tricky to create a functional test to verify this,
but manual testing shows it works fine and fixes the described issue

**Comment by frodonLD** [comment] 2019-12-20 11:41
Hello, 
Plz what about this issue and the solution of described here https://github.com/reactor/reactor-kafka/issues/49#issuecomment-478715349?

**Comment by sarialem** [comment] 2020-05-01 09:59
I just tested code on master (coming in 1.3.0 release), and just doing a `retry()` or `retryWhen()` when it's CommitFailedException, and it continues functioning propperly after partitions re-assignment.

**Comment by venkatagattupalli** [comment] 2020-06-09 06:03
Hi Team any update on when 1.3.0 will be released

**Comment by simonbasle** [comment] 2020-06-09 09:12
@venkatagattupalli 1.3.0 will likely become GA around October this year, as part of the 2020.0 release train (codename Europium). We aim at doing a first milestone on June 22, as indicated in the corresponding [github milestone](https://github.com/reactor/reactor-kafka/milestone/11).

@bsideup looks like work on 1.3 is fixing this issue, should we add it to 1.3.0-M1 ?

**Comment by venkatagattupalli** [comment] 2020-06-10 05:42
hi Team ,I  am using the latest version of reactor kafka (reactor-kafka:1.2.2.RELEASE)  and we are getting this exception in our production 
**"level":"INFO","message":"Attempt to heartbeat failed since group is rebalancing","class":"org.apache.kafka.clients.consumer.internals.AbstractCoordinator","timestamp":"2020-06-10 00:37:27.076 -0400"}.** 
Can we get a link which has sample code to configure the reactor kafka receiver properly with ideal settings in order to solve the rebalance issues

**Comment by bsideup** [comment] 2020-06-10 06:23
@venkatagattupalli there is a bug in reactor-kafka 1.2.x that you're using.
reactor-kafka 1.3.x comes with a major refactoring of internals and no longer has this bug, you can try the latest SNAPSHOTs or wait for the first milestone release (see Simon's comment)

**Comment by venkatagattupalli** [comment] 2020-06-10 23:41
Thank you @bsideup  and @simonbasle  for answering my queries. Could you please let me know if there is an optimal configuration for heartbeat.interval.ms that I need to setup. The reason for asking is I still see the error sometimes during server startup(multiple consumers).Also, I am seeing a weird issue wherein when there are messages in the topic before the server startup and if I see this message during the startup , the consumer is unable to  process the messages

**Comment by venkatagattupalli** [comment] 2020-06-18 21:17
Hi Team ,
Could you please let us know the optimal configuration for KafkaConsumer . I see an issue wherein the polling of messages is different when there are messages in the topic as opposed to when there are no messages in the topic

**Comment by nadimcse** [comment] 2020-06-18 21:52
Hi, I am having the same issue of controlling polling of messages. I also want to control the polling of messages until my messages are acknowledged/committed .

**Comment by bsideup** [comment] 2020-06-22 12:26
reactor-kafka 1.3.0-M1 is out, please give it a try!

**Comment by tarunrathor-pro** [comment] 2020-07-30 07:34
> reactor-kafka 1.3.0-M1 is out, please give it a try!

Does this solve the problem of controlling the polling frequency when my processing speed is slow as mentioned by https://github.com/reactor/reactor-kafka/issues/49#issuecomment-646324459

**Comment by lborisevich-clgx** [comment] 2020-10-16 17:42
@bsideup still seeing the same issue in RC1

**Comment by bsideup** [comment] 2020-10-16 20:40
@lborisevich-clgx what about just released RC2? :)

**Comment by lborisevich-clgx** [comment] 2020-10-18 06:21
@bsideup I'm afraid I'm still seeing the same issue, the moment I add more consumers and rebalancing happens, the consumers start failing committing offset and then send LeaveGroup request, after which they no longer attempt to reconnect or read any messages

**Comment by bsideup** [comment] 2020-10-19 08:47
@lborisevich-clgx could you please provide a reproducer?

**Comment by lborisevich-clgx** [comment] 2020-10-20 23:30
@bsideup usually the issue happens when an additional consumer is added and rebalancing happens, but I tried to reproduce it on a different topic with slightly different data and business logic and the consumer is just fine. I'm trying to get more insight at the moment and will provide more specifics once I have them.

Would there be any specific logs or behavior that I should be looking for? I'm trying to run in debug mode now and see if I can find something useful

**Comment by bsideup** [comment] 2020-10-22 09:51
@lborisevich-clgx I am afraid it would be tough to debug just by looking at the logs. It is also hard to give any tips on what to look for in the debug mode for the same reason...

**Comment by ashmeet-kandhari** [comment] 2021-06-09 13:49
Hi Team, @bsideup 

We are facing the same issue as mentioned in the starting [1]
The observations were
* A rebalancing is triggered ie ReceiverOptions.onPartitionsRevoked 
* Successfully assigned a group ie ReceiverOptions.onPartitionsAssigned 
* The message commits fail as the consumer was kicked out 
* The heartbeat fails 


Queries:
* How to find what triggered a rebalance (where can we find the logs about this trigger)?
* After successful assignment of a group what might cause the kick out/ commits fail?


Configurations:
* Spring-boot version : 2.4.5
* reactor-kafka.version: 1.3.3 


[1] - https://github.com/reactor/reactor-kafka/issues/49#issue-345126361

**Comment by garyrussell** [comment] 2021-06-09 13:57
This is generally caused by your code taking too long to process the records returned by the poll.

You may need to reduce `max.poll.records` and/or increase `max.poll.interval.ms`.

If you add a `.publishOn(...)` before your long running code, the consumer can continue to poll (it will be paused due to back pressure) to keep it alive until you are ready to receive more records.


https://github.com/reactor/reactor-kafka/issues/218

**Comment by ashmeet-kandhari** [comment] 2021-06-09 14:37
@garyrussell Thanks for the response.
Will play around and let you know

Can you also let me know if my understanding is correct for 
* `publishOn(Schedulers.newSingle("willSuspend"), 10)` will run the consumer on single thread only until that thread suspend?

Thanks in advance

**Comment by garyrussell** [comment] 2021-06-09 15:09
It will run the downstream on a single thread, allowing the consumer thread to continue to poll the consumer (it will pause the consumer until the downstream is ready to receive more records and then resume it). You can see this with DEBUG logging.

**Comment by kharel** [comment] 2021-07-10 17:01
Hi Team, @bsideup,

We are using reactor-kafka 1.3.4 and we are experiencing the same problem as initial comment #1
when processing time took longer then max.poll.interval.ms we get an exception but the kafka receiver is not recovered.

Some logs: 
[Consumer clientId=entity-events-dev-product-publisher-consumer, groupId=reactive-test] Error sending fetch request (sessionId=1721031098, epoch=48) to node 3: {}.

org.apache.kafka.common.errors.DisconnectException: null

2021-07-10 19:54:24.991  INFO 38024 --- [| reactive-test] o.a.kafka.clients.FetchSessionHandler    : [Consumer clientId=entity-events-dev-product-publisher-consumer, groupId=reactive-test] Error sending fetch request (sessionId=1564105727, epoch=48) to node 4: {}.

org.apache.kafka.common.errors.DisconnectException: null

2021-07-10 19:54:24.992  INFO 38024 --- [| reactive-test] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=entity-events-dev-product-publisher-consumer, groupId=reactive-test] Group coordinator rhs-nlsvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092 (id: 2147483645 rack: null) is unavailable or invalid, will attempt rediscovery
2021-07-10 19:54:27.125  INFO 38024 --- [reactive-test-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=entity-events-dev-product-publisher-consumer, groupId=reactive-test] Discovered group coordinator rhs-nlsvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092 (id: 2147483645 rack: null)
2021-07-10 19:54:29.372 ERROR 38024 --- [reactive-test-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=entity-events-dev-product-publisher-consumer, groupId=reactive-test] Offset commit failed on partition sd.pbc.dev.semple.entity-events-1 at offset 42: The coordinator is not aware of this member.
2021-07-10 19:54:29.375  WARN 38024 --- [reactive-test-1] r.k.r.internals.DefaultKafkaReceiver     : Commit failed

2021-07-10 19:54:29.379 ERROR 38024 --- [reactive-test-1] r.k.r.internals.DefaultKafkaReceiver     : Consumer flux exception
org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.

2021-07-10 19:54:29.391  INFO 38024 --- [reactive-test-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=entity-events-dev-product-publisher-consumer, groupId=reactive-test] Giving away all assigned partitions as lost since generation has been reset,indicating that consumer is no longer part of the group
2021-07-10 19:54:29.393  INFO 38024 --- [reactive-test-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=entity-events-dev-product-publisher-consumer, groupId=reactive-test] Lost previously assigned partitions sd.pbc.dev.semple.entity-events-1, sd.pbc.dev.semple.entity-events-0
2021-07-10 19:54:29.394  INFO 38024 --- [reactive-test-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=entity-events-dev-product-publisher-consumer, groupId=reactive-test] (Re-)joining group
2021-07-10 19:54:29.399  INFO 38024 --- [reactive-test-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=entity-events-dev-product-publisher-consumer, groupId=reactive-test] Attempt to heartbeat failed for since member id entity-events-dev-product-publisher-consumer-4b63669c-f1de-4407-aa7e-8df857c651ac is not valid.

After this error kafka receiver stops processing messages.

btw, we couldn't find method receiverOptions.receiverExceptionHandler(new LogAndContinueReceiverExceptionHandler()), was it removed?

Please help,
Thanks

**Comment by garyrussell** [comment] 2021-07-12 17:11
You can add a `.repeat()` - see https://github.com/reactor/reactor-kafka/issues/218#issuecomment-826881274 and the issue it links to.

I am not sure what that exception handler reference is; I can't find any evidence of it

**Comment by kharel** [comment] 2021-07-15 17:07
@garyrussell thanks a lot!
will try that

**Comment by kharel** [comment] 2021-07-18 13:56
hi @garyrussell 

using repeat() didn't help.
I think that repeat() resubscribe only on completion, not on error. 
From documentation:
"Repeatedly and indefinitely subscribe to the source upon **completion** of the previous subscription"
"Returns: an indefinitely repeated Flux on **onComplete**"

The only solution I found is as @gzeskas mentioned - re-create entire reactive stream on termination, but it's no so elegant.
Any other suggestions ?

**Comment by simonbasle** [comment] 2021-07-19 07:55
> using repeat() didn't help.

to clarify @garyrussell's comment, it's not `repeat` but `retry` that re-subscribes in case of `onError` termination, so favor that ;)

**Comment by koldat** [comment] 2021-08-31 10:50
Repartitioning cause OOM for me, but maybe it is related together: #237

**Comment by Aniket-Singla** [comment] 2021-09-28 08:43
> thanks @simonbasle
> tried that as well, but now I get the following exception upon retry:
> reactor.core.Exceptions$ReactorRejectedExecutionException: Scheduler unavailable
> at reactor.core.Exceptions.failWithRejected(Exceptions.java:268)
> 
> I added this to my reactive chain:
> .retryWhen(Retry.max(3).transientErrors(true))
> .repeat()
> .subscribe()

Hi @kharel , were you able to solve this issue, I am getting the same if I use retry.

**Comment by Aniket-Singla** [comment] 2021-09-28 08:43
> thanks @simonbasle
> tried that as well, but now I get the following exception upon retry:
> reactor.core.Exceptions$ReactorRejectedExecutionException: Scheduler unavailable
> at reactor.core.Exceptions.failWithRejected(Exceptions.java:268)
> 
> I added this to my reactive chain:
> .retryWhen(Retry.max(3).transientErrors(true))
> .repeat()
> .subscribe()

Hi @kharel , were you able to solve this issue, I am getting the same if I use retry.

**Comment by kharel** [comment] 2021-09-28 09:14
@Aniket-Singla 
I solved it by using commit instead of acknowledge

**Comment by simonbasle** [comment] 2021-09-28 09:15
why is there still a `repeat()` here? careful with `retry()` and `repeat()` (no-arguments), as these place no bounds on the number of re-subscription (which is usually not desirable).

when does the exception occur exactly? isn't there more information / more to the stack trace?

in @kharel's code it is unclear which `Scheduler` was unavailable AND which part of the code is using a `Scheduler` in the first place.

@Aniket-Singla perhaps you can provide a bit more context?

**Comment by Aniket-Singla** [comment] 2021-09-28 09:53
Hi @simonbasle , I am consuming messages in the following way:

```
redemptionEventReactiveKafkaConsumerTemplate
                .receiveAutoAck()
                .doOnNext(consumerRecord -> log.info("received key={}, value={} from topic={}, offset={}",
                        consumerRecord.key(),
                        consumerRecord.value(),
                        consumerRecord.topic(),
                        consumerRecord.offset())
                )
                .map(ConsumerRecord::value)
                .flatMap(this::consume)
                .onErrorContinue((error, value)->log.error("something bad happened while consuming : {}", error.getMessage()))
                .retry(4)
                .subscribe();
```
When kafka commit fails for the first time ( to creating this scenario, I am adding a breakpoint in the consume method):

```
org.apache.kafka.common.errors.DisconnectException: null

2021-09-28 15:16:39.830  WARN [cxinteracts-mp-member-offers,,,] 22812 --- [emption-event-2] r.k.r.internals.DefaultKafkaReceiver     : Commit failed

org.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets.
Caused by: org.apache.kafka.clients.consumer.internals.NoAvailableBrokersException: null

org.apache.kafka.clients.consumer.CommitFailedException: Offset commit cannot be completed since the consumer is not part of an active group for auto partition assignment; it is likely that the consumer was kicked out of the group.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:1116) ~[kafka-clients-2.5.1.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.doCommitOffsetsAsync(ConsumerCoordinator.java:936) ~[kafka-clients-2.5.1.jar:na]
Caused by: org.apache.kafka.clients.consumer.internals.NoAvailableBrokersException: null
```


It retries 4 times as per the code, but throws exception in each retry:

```
2021-09-28 15:16:39.917 ERROR [cxinteracts-mp-member-offers,,,] 22812 --- [     parallel-4] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

reactor.core.Exceptions$StaticRejectedExecutionException: Scheduler unavailable

```

I am creating subscription in spring CommandLineRunner bean.

**Comment by simonbasle** [comment] 2021-09-28 10:01
> I am creating subscription in spring CommandLineRunner bean.

I think that is the issue. Since you call `.subscribe()`, which is *non-blocking*, execution of the `CommandLineRunner` isn't waiting for kafka data. If there isn't any more code after that, the `CommandLineRunner` will terminate, and it is likely that means your app shuts downs and reactor default `Schedulers` get disposed as well at that point.

**Comment by Aniket-Singla** [comment] 2021-09-28 10:20
CommandLineRunner does exits after running run method ( in the main thread ), but the app does not shut down.  Can you please suggest a better place to start subscription in spring application ?

**Comment by simonbasle** [comment] 2021-09-29 12:33
@Aniket-Singla unfortunately the `RejectedException` that you get is a singleton one, which doesn't give us much information as to which `Scheduler` was shut down.

 - A `Scheduler` is somehow in play in your reactive chain (might be the `Schedulers.immediate()` one which is used as "no-op" default by `KafkaReceiver` IIRC).
 - That `Scheduler` is somehow disposed at the point where a `retry` is attempted, even though it is potentially still used.
 - `Schedulers.immediate` would only be disposed by `Schedulers.shutdownNow()` call or `Schedulers.setFactory(f)` call

The `CommandLineRunner` was a prime suspect at something going amiss because of the non-blocking nature of Reactor vs the blocking nature of CLR.

Would you be able to debug, see what Reactor class calls `Exceptions.failWithRejected()` ? This may give us a hint at which `Scheduler` is rejecting tasks here.

**Comment by simonbasle** [comment] 2021-09-29 12:38
PS: @Aniket-Singla this should probably be a separate issue, opened https://github.com/reactor/reactor-kafka/issues/245

**Comment by kharel** [comment] 2021-09-29 12:44
@simonbasle it happened to me as well when I used acknowledge() and I did not add any scheduler from my side. 
so I assumed that the exception is probably referring to scheduler in the reactive kafka itself.

**Comment by garyrussell** [comment] 2022-06-13 16:19
Closing this as it appears that the `retryWhen()` and `repeat()` solves the original issue and the `RejectedException` reported later in the thread is also resolved in current versions.

**Closed by garyrussell** 2022-06-13 16:19 UTC
Labels: type/bug

**Comment by Akshayjain60165** [comment] 2024-05-31 08:28
I am facing a issue in which when I do rollout restart my old consumer leave the group and new consumer joins in the group,
In kafka I am able to see the log of Preparing rebalance but after that Stabilised log is not coming for around 20 mins as after  Stabilisation assignment comes and for 20 mins consumption is stopped.
* What can be the reason for this much of rebalancing? 
* If I poll() before assignment received if this will effect rebalancing?
