### ISSUE TITLE
ConcurrentModificationException during parallel consuming from each partition 

### ISSUE THREAD

**Issue by oemergenc** [reactor/reactor-kafka#193] opened 2021-02-14 20:46 UTC
Hi,

i am trying to consume messages from each existing partition in a cluster using a dedicated `KafkaReceiver` for each single partition. This results in an ConcurrentModificationException and i have no clue why.

The basic code looks like this:

```
        return getAllPartitions(topic, consumerConfig)
            .flatMap { aSinglePartition ->                
                val receiverOptions = ReceiverOptions.create<ByteArray, ByteArray>(consumerConfig)
                    .assignment(listOf(TopicPartition(topic, aSinglePartition.partition())))
                    .addAssignListener { it.forEach { p -> p.seekToBeginning() } }
                val receiver = KafkaReceiver.create(receiverOptions)
                receiver.receiveAutoAck()
                    .flatMap { it }
                    .take(500L)                    
            }
```
I am wondering why there is a ConcurrentModificationException, because i am using a dedicated KafkaReceiver per partition.
I also tried to use one of the other `receive...` method resulting in a very similar problem.

Any hints on this would be greatly appreciated.

## Expected Behavior
No ConcurrentModificationException to be thrown.

## Actual Behavior
A ConcurrentModificationException is thrown although different KafkaReceivers for each partition are used.

The resulting stacktrace looks like this:
```
21:37:55.736 [reactive-kafka-fa65ec78-60fa-4cd3-8fe4-13c49673d353-12] ERROR r.k.r.internals.ConsumerEventLoop - Unexpected exception during close
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2422)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2305)
	at reactor.kafka.receiver.internals.ConsumerEventLoop$CloseEvent.run(ConsumerEventLoop.java:404)
	at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.FluxFromMonoOperator.subscribe(FluxFromMonoOperator.java:83)
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.cancel(FluxUsingWhen.java:342)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:809)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:696)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:587)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.request(FluxFlatMap.java:346)
	at reactor.core.publisher.FluxTake$TakeSubscriber.request(FluxTake.java:166)
	at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:162)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:137)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:137)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:137)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.request(FluxFlatMap.java:1031)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:728)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:568)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:1006)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
	at reactor.core.publisher.FluxTake$TakeSubscriber.onNext(FluxTake.java:127)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:542)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:1006)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:270)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:228)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:986)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8147)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:425)
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onNext(FluxUsingWhen.java:358)
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:353)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:189)
	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:83)
	at reactor.core.scheduler.SingleWorkerScheduler.execute(SingleWorkerScheduler.java:63)
	at reactor.core.scheduler.ExecutorScheduler$ExecutorSchedulerWorker.schedule(ExecutorScheduler.java:242)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.trySchedule(FluxPublishOn.java:312)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onNext(FluxPublishOn.java:237)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:503)
	at reactor.core.publisher.UnicastProcessor.drainRegular(UnicastProcessor.java:387)
	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:469)
	at reactor.core.publisher.UnicastProcessor.tryEmitNext(UnicastProcessor.java:337)
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:97)
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
	at reactor.kafka.receiver.internals.ConsumerEventLoop$PollEvent.run(ConsumerEventLoop.java:250)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by garyrussell** [comment] 2021-03-05 16:07
>21:37:55.736 [reactive-kafka-fa65ec78-60fa-4cd3-8fe4-13c49673d353-12] ERROR r.k.r.internals.ConsumerEventLoop - Unexpected exception during close

The `-12` in the thread name implies that you are (somehow) using a thread pool scheduler with at least 12 threads. It is not clear how that is possible given that the ConsumerEventLoop only runs on a single thread (in 1.3.x).

Are you using an earlier version?

**Comment by oemergenc** [comment] 2021-03-06 14:06
Hey, 

i am using reactor-kafka version 1.3.1. 

I am wondering why the `..-12` looks suspicious to you. As far as i can see the `-12` should come from here:

Starting here:
https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java#L77 

and in the end from here:
https://github.com/reactor/reactor-kafka/blob/1c677186782be613385278fa500316e4bbb8dfaf/src/main/java/reactor/kafka/receiver/internals/KafkaSchedulers.java#L58

As i am using dedicated KafkaReceivers for each partition of a single topic, the `-12` (maybe even higher) make sense in my opinion.
In my cluster, topics have forty partitions and i would like to read each partition with a dedicated KafkaReceiver. When consuming messages from a topic there will be 40 concurrent KafkaReceivers, where each KafkaReceiver reads messages from 1 partition.

Sidenote:
Why am i trying to do this?
I would like to achieve a very high throughput while reading a topic. 
After reading a topic KafkaReceivers will die and do not stay active as i do not need them anymore.

**Comment by garyrussell** [comment] 2021-03-08 17:12
Ah; sorry; I didn't notice the static `AtomicLong` in the thread factory - all my testing has had only one receiver.

That said, clearly, the `close()` is running on a different thread; which should not be possible.

This is the code in `stop()`

```java
    Mono<Void> stop() {
        return Mono
            .defer(() -> {
                log.debug("dispose {}", isActive);

                if (!isActive.compareAndSet(true, false)) {
                    return Mono.empty();
                }

                periodicCommitDisposable.dispose();

                if (consumer == null) {
                    return Mono.empty();
                }

                return Mono.<Void>fromRunnable(new CloseEvent(receiverOptions.closeTimeout()))
                    .as(flux -> {
                        return KafkaSchedulers.isCurrentThreadFromScheduler()
                            ? flux
                            : flux.subscribeOn(eventScheduler);
                    });
            })
            .onErrorResume(e -> {
                log.warn("Cancel exception: " + e);
                return Mono.empty();
            });
    }
```

and

```
    static boolean isCurrentThreadFromScheduler() {
        return Thread.currentThread() instanceof EventThreadFactory.EmitterThread;
    }
```

So the close can run on any scheduler thread, not just this loop's `eventScheduler` - looks wrong to me.

**Comment by garyrussell** [comment] 2021-03-08 19:16
I reproduced it with this test:

```java
    @Test
    public void closeForeignThread() throws InterruptedException {
        this.receiverOptions = this.receiverOptions.pollTimeout(Duration.ofSeconds(60));
        DefaultKafkaReceiver<Integer, String> receiver = createReceiver();
        Disposable dispo = receiver.receive()
                .doOnNext(rec -> { })
                .subscribe();
        Scheduler sched = KafkaSchedulers.newEvent("closeForeignThread2");
        CountDownLatch latch = new CountDownLatch(1);
        sched.schedule(() -> {
            try {
                dispo.dispose();
                latch.countDown();
            }
            catch (ConcurrentModificationException cmex) {
                cmex.printStackTrace();
            }
        });
        assertThat(latch.await(10, TimeUnit.SECONDS)).isTrue();
        /*
         * Nothing to assert - the exception on close is just logged - see
         * the error in the log before the fix.
         */
    }
```

However, since `KafkaSchedulers` is package private; this implies you are closing this consumer from the consumer dispatcher thread of another receiver; this seems to be born out by your stack trace...

```
...
at reactor.kafka.receiver.internals.ConsumerEventLoop$CloseEvent.run(ConsumerEventLoop.java:404)
...
at reactor.kafka.receiver.internals.ConsumerEventLoop$PollEvent.run(ConsumerEventLoop.java:250)
...
```

I can fix the bug, but perhaps you can force a thread switch for the `close()` ?

**Comment by oemergenc** [comment] 2021-03-09 05:33
Hi,

great that you could reproduce the problem.
I think a thread switch would be hard to implement for me. Actually your test exactly describes what i am trying to do. I simplified my problem in the description of this issue, the real problem is more complicated.

I am building an interactive kafka application, where users can start and stop consuming messages. When the user clicks on start the consumption of the topic (e.g. 40 Kafkareceivers..) starts. I am storing a reference to the receiver flux. 
For this i am using `ConnectableFlux`, e.g. something like this: `Disposable dis = connectableflux.publish`
When the user clicks stop, this happens from another thread (ui thread)
`dis.dispose...`

At this point the exception occurs. 
Will this work with your fix for 1.3.3?

**Comment by garyrussell** [comment] 2021-03-09 14:48
It should because, now, the `ConsumerEvenLoop.stop()` always schedules the close on the event thread.

**Comment by oemergenc** [comment] 2021-03-09 17:12
Great, thank you. Looking forward to the 1.3.3 release.

**Closed** 2021-03-10 14:53 UTC
Labels: type/bug
