### ISSUE TITLE
Commit retry has no backoff

### ISSUE THREAD

**Issue by CodeMyWorld** [reactor/reactor-kafka#127] opened 2020-04-08 12:05 UTC
When kafka client commits failed, client will retry immediately after the failed commit request. And after 100 times retry within 10 ms, the comsumer flux is terminated, the consumer will not poll new messages anymore
## Expected Behavior

Retry should have backoff, instead of retrying immediately
## Actual Behavior

Retry commit immediately. By checking the log, the consumer thread retried to commit 100 times within 10ms. This time is not enough for Kafka client failover in a clustered environment.
## Steps to Reproduce

Start the consumer, and then stop one of kafka broker.

## Possible Solution

Add some backoff before next try here:
https://github.com/reactor/reactor-kafka/blob/2e96f8e3a621c7675d33af63015624b81830fbb0/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L587
## Your Environment

* Reactor version(s) used:  3.2.0
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): 11
* OS and version (eg `uname -a`): Ubuntu 18.04

**Comment by garyrussell** [comment] 2020-04-10 19:00
Please explain further; it's not clear to me why the commits are retried at all in this code.

If a rebalance is in progress, it means we have probably lost the partitions anyway (and they may have been assigned to a different instance) so, IMHO, it's completely wrong to retry offset commits.

**Comment by garyrussell** [comment] 2020-04-10 19:10
```
    /**
     * Returns the maximum number of consecutive non-fatal commit failures that are tolerated.
     * For manual commits, failure in commit after the configured number of attempts fails
     * the commit operation. For auto commits, the receive Flux is terminated.
     * @return maximum number of commit attempts
     */
    @NonNull
    int maxCommitAttempts();
```

Commits are retried only for `RetriableCommitFailedException`.

I very much doubt that a failure to commit due to a rebalance would be considered retriable; by definition, we would have lost the partitions and they may have been reassigned to another instance.

**Comment by billydh** [comment] 2020-08-04 23:53
@CodeMyWorld how did you figure out that the time period in which those 100 commit attempts are tried is 10ms? I tried to looking in `ReceiverOptions`, `MutableReceiverOptions` but could not find that 10ms time period.

**Comment by billydh** [comment] 2020-08-05 00:00
@garyrussell is there a way to test the `maxCommitAttempts` at all? i.e. is it possible to write a unit test in my application to simulate that `RetriableCommitFailedException`? my unit tests are all using `EmbeddedKafka`.

**Comment by CodeMyWorld** [comment] 2020-11-05 07:44
@billydh 
the 10ms is not defined. The kafka client just retries after the exception without backoff. 100 retry costs couples of  millseconds.

**Comment by patrickherrera** [comment] 2022-02-24 00:01
I'm seeing this as well.  For example I have just applied a new configuration to our MSK cluster which cycled all the brokers.  Consistently, projects using Reactor-Kafka have issues with this, but non-reactor projects handle it fine.  Here is an example log:
```
Feb 23 22:54:23.881	[Consumer clientId=XXX, groupId=XXX] Discovered group coordinator b-1.msk-general-1.c2.kafka.eu-west-2.amazonaws.com:9094 (id: 2147483646 rack: null)
Feb 23 22:54:23.882	[Consumer clientId=XXX, groupId=XXX] Discovered group coordinator b-1.msk-general-1.c2.kafka.eu-west-2.amazonaws.com:9094 (id: 2147483646 rack: null)
Feb 23 22:54:23.887	[Consumer clientId=XXX, groupId=XXX] Discovered group coordinator b-1.msk-general-1.c2.kafka.eu-west-2.amazonaws.com:9094 (id: 2147483646 rack: null)
Feb 23 22:54:23.959	[Consumer clientId=XXX, groupId=XXX] Offset commit failed on partition dwh.XXX.merged-0 at offset 1102342: The coordinator is loading and hence can't process requests.
Feb 23 22:54:23.960	Commit failed
Feb 23 22:54:23.960	Commit failed with exceptionorg.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets., retries remaining 5
Feb 23 22:54:23.973	[Consumer clientId=XXX, groupId=XXX] Offset commit failed on partition dwh.XXX.merged-0 at offset 1102342: The coordinator is loading and hence can't process requests.
Feb 23 22:54:23.974	Commit failed
Feb 23 22:54:23.974	Commit failed with exceptionorg.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets., retries remaining 4
Feb 23 22:54:24.074	[Consumer clientId=XXX, groupId=XXX] Offset commit failed on partition dwh.XXX.merged-0 at offset 1102342: The coordinator is loading and hence can't process requests.
Feb 23 22:54:24.074	Commit failed
Feb 23 22:54:24.075	Commit failed with exceptionorg.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets., retries remaining 3
Feb 23 22:54:24.175	[Consumer clientId=XXX, groupId=XXX] Offset commit failed on partition dwh.XXX.merged-0 at offset 1102342: The coordinator is loading and hence can't process requests.
Feb 23 22:54:24.175	Commit failed
Feb 23 22:54:24.176	Commit failed with exceptionorg.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets., retries remaining 2
Feb 23 22:54:24.276	[Consumer clientId=XXX, groupId=XXX] Offset commit failed on partition dwh.XXX.merged-0 at offset 1102342: The coordinator is loading and hence can't process requests.
Feb 23 22:54:24.276	Commit failed
Feb 23 22:54:24.276	Commit failed with exceptionorg.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets., retries remaining 1
Feb 23 22:54:24.417	[Consumer clientId=XXX, groupId=XXX] Offset commit failed on partition dwh.XXX.merged-0 at offset 1102342: The coordinator is loading and hence can't process requests.
Feb 23 22:54:24.417	Commit failed
Feb 23 22:54:24.419	[Consumer clientId=XXX, groupId=XXX] Revoke previously assigned partitions dwh.XXX.merged-0
Feb 23 22:54:24.419	[Consumer clientId=XXX, groupId=XXX] Member XXX-6ddfc36c-08c6-4723-beff-4389a2009b62 sending LeaveGroup request to coordinator b-1.msk-general-1.c2.kafka.eu-west-2.amazonaws.com:9094 (id: 2147483646 rack: null) due to the consumer is being closed
Feb 23 22:54:24.420	[Consumer clientId=XXX, groupId=XXX] Resetting generation due to: consumer pro-actively leaving the group
Feb 23 22:54:24.420	[Consumer clientId=XXX, groupId=XXX] Request joining group due to: consumer pro-actively leaving the group
Feb 23 22:54:24.421	[Consumer clientId=XXX, groupId=XXX] LeaveGroup request with Generation{generationId=3978, memberId='XXX-6ddfc36c-08c6-4723-beff-4389a2009b62', protocol='range'} failed with error: The coordinator is loading and hence can't process requests.
Feb 23 22:54:24.421	Metrics scheduler closed
Feb 23 22:54:24.422	Closing reporter org.apache.kafka.common.metrics.JmxReporter
Feb 23 22:54:24.422	Metrics reporters closed
Feb 23 22:54:24.424	App info kafka.consumer for XXX unregistered
Feb 23 22:54:24.424	Operator called default onErrorDropped
```

It retries as requested, but there is no backoff between each retry so it is all over in about a second and the consumer is unregistered and only a restart brings it back at this stage.  I'm looking to write my own watchdog to restart consumers somehow, but the retry is not very useful as it stands (although I'm going to experiment right now with a very large number to see if it does recover successfully).

**Comment by patrickherrera** [comment] 2022-02-24 02:09
FWIW, I bumped up the retry to a large number by adding zeros to my original value (600,000!) and did a complete broker reboot cycle.  This time around it worked fine after only 64 retries, which took about 70 seconds overall.  Obviously there are other variables at play to determine that number for your cluster, but it proves that it does work and can recover.

**Comment by garyrussell** [comment] 2022-02-24 21:57
@patrickherrera I think I am close to a solution; hopefully I'll have something for you to try early next week.

**Comment by patrickherrera** [comment] 2022-02-24 22:10
Thanks @garyrussell, no stress.  When you are ready I can readily reproduce the issue so happy to test

**Comment by garyrussell** [comment] 2022-03-01 19:50
@patrickherrera PR issued; if you want to try it, you can build 1.3.11-SNAPSHOT from my branch https://github.com/garyrussell/reactor-kafka/tree/GH-127

**Comment by patrickherrera** [comment] 2022-03-02 21:29
Thanks @garyrussell, that worked for me. I see that it waited about 500ms between each attempt and it took only 3 retries to re-establish connectivity
```
Mar 02 21:16:08.287	[Consumer clientId=XXX, groupId=XXX] Offset commit failed on partition XXX-0 at offset 19492760: The coordinator is loading and hence can't process requests.
Mar 02 21:16:08.287	Commit failed
Mar 02 21:16:08.287	Commit failed with exceptionorg.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets., retries remaining 599999
Mar 02 21:16:08.888	[Consumer clientId=XXX, groupId=XXX] Offset commit failed on partition XXX-0 at offset 19492760: The coordinator is loading and hence can't process requests.
Mar 02 21:16:08.889	Commit failed
Mar 02 21:16:08.889	Commit failed with exceptionorg.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets., retries remaining 599998
Mar 02 21:16:09.490	[Consumer clientId=XXX, groupId=XXX] Offset commit failed on partition XXX-0 at offset 19492760: The coordinator is loading and hence can't process requests.
Mar 02 21:16:09.490	Commit failed
Mar 02 21:16:09.490	Commit failed with exceptionorg.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing the latest consumed offsets., retries remaining 599997
```

**Comment by garyrussell** [comment] 2022-03-02 21:35
@patrickherrera Excellent - thanks for your help in testing this.

**Closed** 2022-03-11 16:07 UTC
Labels: type/bug
