### ISSUE TITLE
How to share KafkaReceiver between webclients ? 

### ISSUE THREAD

**Issue by xmlking** [reactor/reactor-kafka#11] opened 2017-08-14 00:09 UTC
How to share KafkaReceiver between webclients ?
I am getting `Multiple subscribers are not supported for KafkaFlux` error
Is it possible to keep `KafkaReceiver` alive when when all WebClients disconnect ?

```kotlin
@Configuration
class KafkaReceiverConfiguration(
        @Value("\${spring.kafka.consumer.bootstrapServers}")
        private val bootstrapServers: String,

        @Value("\${spring.kafka.consumer.group-id}")
        private val groupId: String,

        @Value("\${spring.kafka.consumer.key-deserializer}")
        private val keyDeserializer: String,

        @Value("\${spring.kafka.consumer.value-deserializer}")
        private val valueDeserializer: String,

        @Value("\${spring.kafka.template.default-topic}")
        private val topic: String

) {

    @Bean
    fun kafkaDataReceiver(): KafkaReceiver<String, String> {
        val consumerProps = mapOf(
                BOOTSTRAP_SERVERS_CONFIG to bootstrapServers,
                GROUP_ID_CONFIG to groupId,
                KEY_DESERIALIZER_CLASS_CONFIG to keyDeserializer,
                VALUE_DESERIALIZER_CLASS_CONFIG to valueDeserializer
        )
        val receiverOptions = ReceiverOptions.create<String, String>(consumerProps)
                .subscription(setOf(topic))

        return KafkaReceiver.create(receiverOptions)
    }
}
```

```kotlin
@Service
class LogService(val kafkaDataReceiver: KafkaReceiver<String, String>) {
    val logStream: Flux<String> by lazy {
        kafkaDataReceiver.receive()
                .map { it.value() }
                .share()
                .log()
    }
}

@Component
class StreamHandler( val logService: LogService) {
    fun fetchLogs(req: ServerRequest) = ok()
            .contentType(APPLICATION_STREAM_JSON)
            .body(logService.logStream, String::class.java)

    fun fetchLogsSSE(req: ServerRequest) = ok()
            .contentType(TEXT_EVENT_STREAM)
            .body(logService.logStream, String::class.java)
}

@Configuration
class StreamRoutes(val streamHandler: StreamHandler) {

    @Bean
    fun logRouter() = router {
        GET("/sse/logs").nest {
            accept(TEXT_EVENT_STREAM, streamHandler::fetchLogsSSE)
            accept(APPLICATION_STREAM_JSON, streamHandler::fetchLogs)
        }
    }

}
```

**Comment by xmlking** [comment] 2017-08-15 21:51
I got some success with following workaround to keep `kafkaReceiver` alive.  i.e., declaring `logStream` as local variable in `StreamHandler`
I still need to create a fake subscriber to prevent it from unsubscribing when all web clients are closed. 

```kotlin
@Component
class StreamHandler(final val kafkaDataReceiver: KafkaReceiver<String, String>,
                    final val objectMapper: ObjectMapper) {
        final val logStream = kafkaDataReceiver.receive().map { objectMapper.readValue(it.value(), Log::class.java)  }.log("StreamHandler").share()

    init{
        logStream.subscribe {
                //TODO: fake subscriber to keep kafka connect active
        }
    }
    fun fetchLogsSSE(req: ServerRequest) = ok()
            .contentType(TEXT_EVENT_STREAM)
            .body(logStream, Log::class.java)

    fun fetchLogs(req: ServerRequest) = ok()
            .contentType(APPLICATION_STREAM_JSON)
            .body(logStream, Log::class.java)
}
```

**Comment by ilayaperumalg** [comment] 2017-09-11 12:22
Hi @xmlking 

Thanks for reporting and sorry for the delay responding to your question.

By design, the Kafka Receiver doesn't support multiple subscribers subscribing to the Flux on Kafka Receiver. One of the main reasons is to use the Kafka consumer model natively.

On the first one you posted, I don't see how you subscribe to the `logStream`. Maybe you are trying to create the Receiver's consumer Flux more than one times.

In the case where you worked around this situation, it is made sure that there is a single subscriber based on your fake subscriber invocation.

It might be worth conditionally operating your routes from the actual subscribe method itself. This way you keep the single subscription model as well you have all your subscriber logic inside the actual subscribe method.

You can see a sample [here](https://github.com/reactor/reactor-kafka/blob/master/reactor-kafka-samples/src/main/java/reactor/kafka/samples/SampleConsumer.java#L80)

**Comment by ilayaperumalg** [comment] 2017-09-15 06:16
@xmlking Closing this for now. Please feel free to re-open if you need more information or have any suggestion on this. Thanks!

**Closed by ilayaperumalg** 2017-09-15 06:16 UTC

**Comment by ThomasBorghs** [comment] 2018-09-15 18:08
@xmlking 

Probably a fair bit late with my answer, but I was faced with a similar challenge as you last week: Several web clients connecting to a backend server sent events stream. I implemented this using the ConnectableFlux construct from Reactor, as documented here: http://projectreactor.io/docs/core/release/reference/#advanced-broadcast-multiple-subscribers-connectableflux.

ConnectableFlux allows you to keep the KafkaReceiver open and subscribe clients through SSE dynamically. For my use case I implemented this as follows (an extract from my Spring WebFlux RequestHandler):

````
// the wrapped KafkaReceiver
private final ConnectableFlux<ServerSentEvent<NetworkPointEvent>> eventPublisher;

public RequestHandler(Map<String, Object> config) {
    // conversion to ConnectableFlux. 
    // Alternative to "publish is "replay"
    // which resends all past received Kafka Messages to each new observer
    eventPublisher = kafkaReceiver.receive()
        .map(consumerRecord -> ServerSentEvent.builder(consumerRecord.value()).build())
        .publish();

    // subscribes to the KafkaReceiver -> starts consumption (without observers attached)
    eventPublisher.connect();
}

public RouterFunction<ServerResponse> getRouterFunction() {
    return RouterFunctions.route(GET("/kafka-messages"), this::subscribeToMessages);
}

private Mono<ServerResponse> subscribeToMessages(ServerRequest serverRequest) {
    return ServerResponse.status(HttpStatus.OK).body(BodyInserters.fromServerSentEvents(eventPublisher));
}
````

Hope this still provides some use to anyone!

**Comment by xmlking** [comment] 2018-09-15 20:04
Thanks @ThomasBorghs will try this solution 
Here is my code base 

https://github.com/xmlking/microservices-observability/blob/master/stream-service/src/main/kotlin/com/example/StreamApplication.kt

**Comment by yaochaoutokyo** [comment] 2021-08-30 13:42
I solved the problem by transforming the KafkaFlux to a shared flux
![image](https://user-images.githubusercontent.com/44495307/131348508-9bbc9ee6-3ea9-4be2-8e3d-a8f90e590aa2.png)
