### ISSUE TITLE
How do we create multiple consumers in the same group in Reactor Kafka ?

### ISSUE THREAD

**Issue by sjuyal12** [reactor/reactor-kafka#168] opened 2020-08-27 18:48 UTC
I am facing issue configuring multiple consumers in the same Consumer group in Reactor Kafka

**Comment by bsideup** [comment] 2020-08-28 15:44
Duplicate of https://github.com/reactor/reactor-kafka/issues/167

**Closed by bsideup** 2020-08-28 15:44 UTC
Labels: status/duplicate
