### ISSUE TITLE
OverflowException in DefaultKafkaSender

### ISSUE THREAD

**Issue by mlex** [reactor/reactor-kafka#30] opened 2018-04-16 12:13 UTC
We noticed the following exception in our test environment:

```
reactor.core.Exceptions$OverflowException: Queue is full: Reactive Streams source doesn't respect backpressure
        at reactor.core.Exceptions.failWithOverflow(Exceptions.java:215)
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onNext(FluxPublishOn.java:221)
```

We were not able to reliably reproduce the issue. But by adding additional logging, we could track it down to the unguarded onNext call in https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java#L349 which does not respect backpressure coming from the `publishOn` operator in https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java#L116.

The `senderOptions.scheduler()` which is used in this case defaults to `Schedulers.single()`. We have multiple `KafkaSenders` active and by default they all share the same scheduler instance. Perhaps this is relevant - I'm not sure.

We use the following code to initialize the senders - note that we do not do any heavy calculation with the result returned from `KafkaSender.send`:
```
kafkaSender.send(
        recordFlux
            .onBackpressureDrop(e -> reportDropping(e))
        .doOnNext(elem -> reportSuccess(elem))
        .doOnError(e -> reportError(e))
        .subscribe();
```

**Comment by OlegDokuka** [comment] 2018-06-27 07:20
@mlex could you show an example that can reproduce issue, pleas? From my point of view it does not seem to be an `KafkasSender` issue because the real demand is under the control of the final `Subscriber` (https://github.com/reactor/reactor-kafka/blob/master/src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java#L250). The only option why it may happend is the `Publisher` that do not respect `Subscriber`'s demand .Thus it would be very usefull to see at some example code that may reproduce that issue.

**Comment by bsideup** [comment] 2021-01-08 12:17
Should be fixed in `1.3.0.RELEASE`

**Closed by bsideup** 2021-01-08 12:17 UTC
Labels: type/bug
